### ISSUE TITLE
--region isn't fully supported

### ISSUE THREAD

**Issue by gavacho** [cuttlesoft/ecs-deploy.py#12]
I attempted to call ecs-deploy-py like so:

```bash
ecs-deploy-py --region us-west-1 --cluster my-cluster --service-name my-service --image "docker.io/myorg/myrepo:${TRAVIS_COMMIT}"
```

But I get the following error:
```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.2/bin/ecs-deploy-py", line 11, in <module>
    sys.exit(CLI())
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/ecs_deploy.py", line 31, in __init__
    self.client = boto3.client('ecs', **credentials)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/boto3/__init__.py", line 83, in client
    return _get_default_session().client(*args, **kwargs)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/botocore/session.py", line 836, in create_client
    client_config=config, api_version=api_version)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/botocore/client.py", line 70, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/botocore/client.py", line 224, in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/botocore/args.py", line 45, in get_client_args
    endpoint_url, is_secure, scoped_config)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/botocore/args.py", line 103, in compute_client_args
    service_name, region_name, endpoint_url, is_secure)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/botocore/client.py", line 297, in resolve
    service_name, region_name)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/botocore/regions.py", line 122, in construct_endpoint
    partition, service_name, region_name)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/botocore/regions.py", line 135, in _endpoint_for_partition
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.
```

I can avoid the error if I execute ecs-deploy-py like this:

```bash
AWS_DEFAULT_REGION=us-west-1 ecs-deploy-py --cluster my-cluster --service-name my-service --image "docker.io/myorg/myrepo:${TRAVIS_COMMIT}"
```

**Comment by samirbaaz** [comment]
This should be fixed when this PR is merged in:

https://github.com/cuttlesoft/ecs-deploy.py/pull/16
